#!/bin/bash

# Open up the docker socket so that our container can talk to it
sudo chmod 777 /var/run/docker.sock

docker run -d --restart="always" --name node-dev-container --hostname dev --net="host" --device /dev/i2c-1 -v /var/run/docker.sock:/var/run/docker.sock:rw -v /var/lib/systemd/clock:/var/lib/systemd/clock:rw toddbu/node-dev-container:1.0
